image: maven:latest

stages: 
  - Clean
  - Test
  - Packet

Clean: 
  stage: Clean
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  
Test:
  stage: Test
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: on_success

Packet:
  stage: Packet
  dependencies:
    - Test
  script:
    - mvn $MAVEN_CLI_OPTS package

only:
  - master

